palworld:
  dir: "D:\\Game\\SteamCMD\\steamapps\\common\\PalServer\\Pal\\Saved\\SaveGames\\0\\259201A849EBE1C85131B0ADF18F8F7A"
#  files: #none for copying the whole folder
#    - "Level.sav"
  copyTo: "D:\\Game\\SteamCMD\\steamapps\\common\\PalServer\\Pal\\Saved\\SaveGames\\0\\backup"
  compression: true
  minimumInterval: "5m" #unit: "s", "m", "h"    , not less than 1s
  timeToDeleteOld: "168h" #Not implemented
  countTodeleteOld: 0 #Not implemented

